#!/usr/bin/env ruby
#^syntax detection

forge "https://forgeapi.puppetlabs.com"

mod 'puppetlabs-stdlib', '>= 3.0.0'

mod 'nike/vault',
  :git => 'https://github.com/nike-inc/cerberus-vault-puppet-module.git'

mod 'nike/consul',
  :git => 'https://github.com/nike-inc/cerberus-consul-puppet-module.git'