#!/usr/bin/env ruby
#^syntax detection

forge "http://forge.puppetlabs.com"

mod 'nike/vault',
  :git => 'https://github.com/fieldju/cerberus-vault-puppet-module.git'

mod 'nike/consul',
  :git => 'https://github.com/fieldju/cerberus-consul-puppet-module.git'

mod 'puppetlabs-stdlib', '4.13.1'